services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: a_stor_shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: a_stor_shop
      DATABASE_URL: postgresql://postgres:postgres@db/a_stor_shop
      SECRET_KEY: your-secret-key
    ports:
      - "5000:5000"
    depends_on:
      - db

  report-generator:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: a_stor_shop
      DATABASE_URL: postgresql://postgres:postgres@db/a_stor_shop
      FLASK_APP: run.py
    command: >
      bash -c "while true; do flask generate-reports; sleep 20; done"
    depends_on:
      - db

volumes:
  postgres_data:
