services:
#  web:
#    build: .
#    ports:
#      - "5000:5000"
#    volumes:
#      - .:/app
#    environment:
#      - FLASK_APP=run.py
#      - FLASK_ENV=development
#      - DATABASE_URL=postgresql://postgres:postgres@db/a_stor_shop
#    depends_on:
#      - db
#    restart: always

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=a_stor_shop
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@astor.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: