version: '3.8'

services:

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: a_stor_shop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@astor.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:5000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/a_stor_shop
      SECRET_KEY: secretkey
    depends_on:
      - db
    restart: always

  report-generator:
    build: .
    volumes:
      - reports_data:/app/reports
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/a_stor_shop
      FLASK_APP: run.py
    depends_on:
      - db
    command: >
      bash -c "while true; do flask generate-reports; sleep 20; done"
    restart: always

volumes:
  postgres_data:
  reports_data:
