services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: a_stor_shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  init-db:
    build: .
    environment:
      SECRET_KEY: p@ss_t-r*ing
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: a_stor_shop
      DATABASE_URL: postgresql://postgres:postgres@db/a_stor_shop
    depends_on:
      - db
    command: >
      bash -c "
        until pg_isready -h \$DB_HOST -p \$DB_PORT -U \$DB_USER -d \$DB_NAME; do
          echo 'Waiting for Postgres...'; sleep 2;
        done;
        echo 'Creating tables...';
        python - <<'PYCODE'
            from app import create_app, db
            app = create_app()
            with app.app_context():
                db.create_all()
            PYCODE
        "

  web:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: a_stor_shop
      DATABASE_URL: postgresql://postgres:postgres@db/a_stor_shop
      SECRET_KEY: p@ss_t-r*ing
    ports:
      - "5000:5000"
    depends_on:
      - db

  report-generator:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: a_stor_shop
      DATABASE_URL: postgresql://postgres:postgres@db/a_stor_shop
      FLASK_APP: run.py
      SECRET_KEY: p@ss_t-r*ing
    command: >
      bash -c "while true; do flask generate-reports; sleep 20; done"
    depends_on:
      - db

volumes:
  postgres_data:
